### ISSUE TITLE
Java: Prepare packaging for V1.0 RC releases of the Semantic Kernel for Java

### ISSUE THREAD

**Issue by d3r3kk** [microsoft/semantic-kernel-java#15]
Tidying up of POMS, testing of packages, bumping depndency versions, etc...
```[tasklist]
### Tasks
- [ ] Update README files to match new code.
- [x] Code formatting
- [x] Merge all feature branches that are relevant
- [x] Do the MVN release task
- [x] Remove SK V1 from the samples
- [x] Remove the "ignored" directories
- [ ] Do a pass to cull any dead code paths
```
