### ISSUE TITLE
Java: Add Agent/Assistant support for OpenAI 

### ISSUE THREAD

**Issue by johnoliver** [microsoft/semantic-kernel-java#19]
Investigate how to integrate assistants into the Java  library
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel-java/issues/181
- [ ] https://github.com/microsoft/semantic-kernel-java/issues/182
- [ ] https://github.com/microsoft/semantic-kernel-java/issues/183
- [ ] https://github.com/microsoft/semantic-kernel-java/issues/184
- [ ] https://github.com/microsoft/semantic-kernel-java/issues/185
- [ ] https://github.com/microsoft/semantic-kernel-java/issues/207
```
