### ISSUE TITLE
Java: Create and publish Maven Archetype for get started projects

### ISSUE THREAD

**Issue by brunoborges** [microsoft/semantic-kernel-java#54]
Create and publish a Maven Archetype that can be used by developers to start a project with Semantic Kernel for Java.
```[tasklist]
### Tasks
- [ ] Java: Define archetype structure and requirements
- [ ] Java: Create archetype folder and implement requirements
- [ ] Java: Configure archetype publishing as part of SK for Java release process
- [ ] Java: Add documentation on how to use the archetype
- [ ] Java: Adjust the main/README to add Get Started with Java Archetype for SK
```
